COMMAND = gcc -Wall -std=gnu11

all:
	$(COMMAND) -c main.c -o main.o
	$(COMMAND) main.o -o main

test:
	make clean
	make all
	rm -f results.txt
	@for format in "1 6000 3000" \
			"4 5000 3000" \
			"512 5000 2000" \
			"1024 4000 2000" \
			"4096 3000 2000" \
			"8192 3000 2000 "; do \
		set -- $$format;\
		./main generate file1 $$2 $$1 ;\
		./main generate file2 $$3 $$1 ;\
		echo "\n" >> results.txt;\
		for type in lib sys; do \
			echo "$$type \n ">> results.txt ;\
			./main copy file1 file1_$$type $$2 $$1 $$type >> results.txt;\
			 ./main copy file2 file2_$$type $$3 $$1 $$type >> results.txt;\
			 ./main sort file1_$$type $$2 $$1 $$type >> results.txt;\
			 ./main sort file1_$$type $$3 $$1 $$type >> results.txt;\
			 rm file1_$$type;\
			 rm file2_$$type;\
		done	;\
		echo "\n" >> results.txt;\
	done
	rm file1 file2
	make clean

clean:
	rm -f *.o main
